Repository TicketPing/TicketPing, pull requests merged in 2024-10, with the labels that each got.

#5 [feat #4] performance 도메인 추가
  services/performance/src/main/java/com/ticketPing/performance/PerformanceApplication.java
  services/performance/src/main/java/com/ticketPing/performance/application/DataLoader.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/PerformanceHallResponseDto.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/PerformanceResponseDto.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/PerformanceScheduleResponseDto.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/PerformanceHallService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/PerformanceService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/entity/Performance.java
  services/performance/src/main/java/com/ticketPing/performance/domain/entity/PerformanceHall.java
  services/performance/src/main/java/com/ticketPing/performance/domain/entity/PerformanceSchedule.java
  services/performance/src/main/java/com/ticketPing/performance/domain/entity/SeatCost.java
  services/performance/src/main/java/com/ticketPing/performance/domain/entity/SeatRate.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceHallRepository.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceRepository.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceScheduleRepository.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/SeatCostRepository.java
  services/performance/src/main/java/com/ticketPing/performance/http/Performance.http
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/PerformanceController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/PerformanceHallController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/response/exception/PerformanceExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/response/success/PerformanceSuccessCase.java
  services/performance/src/main/resources/application.properties
  services/performance/src/main/resources/application.yml
Labels: feature

#23 [feat #19] 결제 요청 api 생성
  services/payment/build.gradle
  services/payment/src/main/java/com/ticketPing/payment/application/dto/PaymentRequestDto.java
  services/payment/src/main/java/com/ticketPing/payment/application/dto/PaymentResponseDto.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/PaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/domain/enums/PayType.java
  services/payment/src/main/java/com/ticketPing/payment/domain/enums/PaymentStatus.java
  services/payment/src/main/java/com/ticketPing/payment/domain/model/Payment.java
  services/payment/src/main/java/com/ticketPing/payment/domain/model/Receipt.java
  services/payment/src/main/java/com/ticketPing/payment/domain/repository/PaymentRepository.java
  services/payment/src/main/java/com/ticketPing/payment/domain/repository/PaymentRepositoryImpl.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/configuration/TossPaymentConfig.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/repository/PaymentJpaRepository.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/PaymentController.java
  services/payment/src/main/resources/application.properties
  services/payment/src/main/resources/application.yml
  services/payment/src/main/resources/static/style.css
  services/payment/src/main/resources/templates/checkout.html
  services/payment/src/main/resources/templates/fail.html
  services/payment/src/main/resources/templates/success.html
  services/payment/src/test/java/com/ticketPing/payment/application/dto/PaymentRequestDtoTest.java
Labels: feature

#27 [refactor #24] LoggingAspect 클래스 Common 모듈 이동
  common/build.gradle
  common/src/main/java/aop/LoggingAspect.java
Labels: refactor

#29 대기열 상태 확인 polling api 생성 & common 모듈 GlobalExceptionHandler 클래스 handleFeignException 메서드 추가
  common/build.gradle
  common/src/main/java/exception/GlobalExceptionHandler.java
  services/client-channel/build.gradle
  services/client-channel/src/main/java/com/ticketPing/client_channel/ClientChannelApplication.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/application/client/QueueManageClient.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/application/client/QueueManageClientAdapter.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/application/dto/WaitingQueueInfoResponse.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/application/service/QueueInfoPollingService.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/application/service/QueueInfoPollingServiceImpl.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/domain/cases/ClientErrorCase.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/domain/cases/ClientSuccessCase.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/infrastructure/annotation/FeignClientAdapter.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/presentation/controller/QueueInfoPollingController.java
  services/queue-manage/build.gradle
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/QueueManageApplication.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/EnterWaitingQueueResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/WaitingQueueInfoResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/mapper/ObjectMapperBasedVoMapper.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepositoryImpl.java
Labels: feature

#30 [feat #18] 회원 로그인 api 생성
  .gitignore
  auth/Dockerfile
  auth/build.gradle
  auth/src/main/java/com/ticketPing/auth/AuthApplication.java
  auth/src/main/java/com/ticketPing/auth/application/dto/request/LoginRequest.java
  auth/src/main/java/com/ticketPing/auth/application/dto/response/LoginResponse.java
  auth/src/main/java/com/ticketPing/auth/application/service/AuthService.java
  auth/src/main/java/com/ticketPing/auth/domain/entity/Gender.java
  auth/src/main/java/com/ticketPing/auth/domain/entity/User.java
  auth/src/main/java/com/ticketPing/auth/domain/repository/UserRepository.java
  auth/src/main/java/com/ticketPing/auth/infrastructure/repository/UserJpaRepository.java
  auth/src/main/java/com/ticketPing/auth/presentation/controller/AuthController.java
  auth/src/main/java/com/ticketPing/auth/presentation/status/AuthErrorCase.java
  auth/src/main/java/com/ticketPing/auth/presentation/status/AuthSuccessCase.java
  auth/src/main/java/com/ticketPing/auth/presentation/status/UserInfoErrorMessage.java
  auth/src/main/java/com/ticketPing/auth/security/JwtUtil.java
  auth/src/main/java/com/ticketPing/auth/security/Role.java
  auth/src/main/java/com/ticketPing/auth/security/SecurityConfig.java
  auth/src/main/resources/application.properties
  auth/src/main/resources/application.yml
  docker-compose.yml
Labels: feature

#33 [feat #32] 토큰 이동 스케줄러 구현 (대기열 -> 처리열)
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/QueueManageApplication.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/EnterWaitingQueueResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/scheduler/TokenTransferScheduler.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/DequeueCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/EnqueueCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/RetrieveTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/RetrieveTopTokensCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/CacheTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/CountAvailableSlotsCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/IncrementCounterCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/AvailableSlots.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WaitingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WorkingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/enums/QueueName.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/enums/QueueStatus.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/service/WaitingQueueDomainService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/service/WaitingQueueDomainServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/service/WorkingQueueDomainService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/service/WorkingQueueDomainServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedissonConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/utils/YmlLoader.java
Labels: feature

#39 [feat #38] 작업열 토큰 조회 api 생성
  services/client-channel/src/main/java/com/ticketPing/client_channel/presentation/controller/QueueInfoPollingController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/waitingQueue/EnterWaitingQueueResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/waitingQueue/WaitingQueueInfoResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/workingQueue/WorkingQueueTokenResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueApplicationService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/RetrieveTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WaitingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WorkingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/enums/TokenStatus.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/cases/QueueErrorCase.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/cases/QueueSuccessCase.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WaitingQueueController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
Labels: feature

#43 [feat #37] auth 서비스 회원 검증 구현
  auth/src/main/java/com/ticketPing/auth/application/dto/LoginResponse.java
  auth/src/main/java/com/ticketPing/auth/application/service/AuthService.java
  auth/src/main/java/com/ticketPing/auth/domain/repository/UserRepository.java
  auth/src/main/java/com/ticketPing/auth/presentation/cases/AuthErrorCase.java
  auth/src/main/java/com/ticketPing/auth/presentation/cases/AuthSuccessCase.java
  auth/src/main/java/com/ticketPing/auth/presentation/cases/UserInfoErrorMessage.java
  auth/src/main/java/com/ticketPing/auth/presentation/controller/AuthController.java
  auth/src/main/java/com/ticketPing/auth/presentation/request/LoginRequest.java
  auth/src/main/java/com/ticketPing/auth/security/JwtUtil.java
Labels: feature

#47 [feat #46] 토큰 이동 스케줄러 ShedLock 적용
  services/queue-manage/build.gradle
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/scheduler/TokenTransferScheduler.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/RetrieveWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/CountAvailableSlotsCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/RetrieveWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WaitingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WorkingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/utils/QueueTokenValueGenerator.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/ShedLockConfig.java
Labels: feature

#48 [feat #40 #41 #42] : 주문 결제 완료후 Redis와 DB 저장
  dtos/order-dto/src/main/java/dto/OrderPaymentDto.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderCreateResponseDto.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/mapper/ObjectMapperBasedVoMapper.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/entity/OrderSeatRedis.java
  services/order/src/main/java/com/ticketPing/order/domain/repository/OrderSeatRedisRepository.java
  services/order/src/main/java/com/ticketPing/order/orderHttp/OrderHttp.http
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/order/src/main/java/com/ticketPing/order/presentation/response/exception/OrderExceptionCase.java
  services/order/src/main/java/com/ticketPing/order/presentation/response/success/OrderSuccessCase.java
  services/order/src/test/java/com/ticketPing/order/service/OrderServiceTest.java
Labels: feature

#51 [feat #50] RedisExpirationListener 구현
  services/client-channel/src/main/java/com/ticketPing/client_channel/application/client/QueueManageClientAdapter.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/application/dto/GeneralTokenResponse.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/application/service/QueueInfoPollingService.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/application/service/QueueInfoPollingServiceImpl.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/infrastructure/client/QueueManageClient.java
  services/client-channel/src/main/java/com/ticketPing/client_channel/presentation/controller/QueueInfoPollingController.java
  services/queue-manage/build.gradle
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/EnterWaitingQueueResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/GeneralTokenResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/scheduler/TokenTransferScheduler.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueApplicationService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/DequeueFirstWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/DequeueWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/EnqueueWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/RetrieveTopWaitingTokensCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/RetrieveWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/CountAvailableSlotsCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/DequeueWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/EnqueueWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/RetrieveWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WaitingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WorkingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/enums/QueueName.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/utils/QueueTokenValueGenerator.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/ShedLockConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/redis/RedisConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/redis/RedisExpirationListener.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/redis/RedissonConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/utils/YmlLoader.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WaitingQueueController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
Labels: feature

#54 payment 예매 호출 api 수정 및 docker-compose.yml payment port number 수정
  docker-compose.yml
  services/payment/src/main/java/com/ticketPing/payment/application/service/StripePaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/cases/PaymentErrorCase.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/repository/PaymentJpaRepository.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/StripePaymentController.java
Labels: feature

#56 fix: common 디렉토리 구조 변경으로 인한 에러 해결
  services/payment/src/main/java/com/ticketPing/payment/application/service/StripePaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/cases/PaymentErrorCase.java
  services/payment/src/main/java/com/ticketPing/payment/cases/PaymentSuccessCase.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/StripePaymentController.java
  services/payment/src/main/resources/application.yml
Labels: bug

#59 [feat #58] docker-compose-build 파일 추가
  docker-compose-build.yml
  docker-compose.yml
  services/queue-manage/src/main/resources/application.yml
Labels: feature

#60 [feat #31] gateway 라우팅 추가
  build.gradle
  docker-compose-build.yml
  docker-compose.yml
  gateway/Dockerfile
  gateway/build.gradle
  gateway/src/main/java/com/ticketping/gateway/GatewayApplication.java
  gateway/src/main/java/com/ticketping/gateway/config/RouteConfig.java
  gateway/src/main/resources/application.yml
  gateway/src/test/java/com/ticketping/gateway/GatewayApplicationTests.java
  services/order/src/main/resources/application.yml
  settings.gradle
Labels: feature

#62 [feat #61] gatling 대기열 부하 테스트
  services/queue-manage/build.gradle
  services/queue-manage/src/gatling/java/simulation/WaitingQueueSimulation.java
Labels: feature

#64 [Fix] payment 에러 수정 및 환경변수 세팅
  .gitignore
  docker-compose.yml
  services/payment/.dockerignore
  services/payment/src/main/java/com/ticketPing/payment/PaymentApplication.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/StripePaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/cases/PaymentSuccessCase.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/StripePaymentController.java
  services/payment/src/main/resources/application.yml
Labels: bug

#69 [feat, fix #68] 사용자 서비스 버그 수정 및 리팩토링
  dtos/user-dto/src/main/java/response/UserResponse.java
  services/user/src/main/java/com/ticketPing/user/application/dto/UserResponse.java
  services/user/src/main/java/com/ticketPing/user/application/service/UserService.java
  services/user/src/main/java/com/ticketPing/user/domain/entity/Gender.java
  services/user/src/main/java/com/ticketPing/user/domain/entity/User.java
  services/user/src/main/java/com/ticketPing/user/presentation/cases/UserErrorCase.java
  services/user/src/main/java/com/ticketPing/user/presentation/cases/UserInfoErrorMessage.java
  services/user/src/main/java/com/ticketPing/user/presentation/cases/UserSuccessCase.java
  services/user/src/main/java/com/ticketPing/user/presentation/controller/UserController.java
  services/user/src/main/java/com/ticketPing/user/presentation/request/CreateUserRequest.java
  services/user/src/main/resources/application.yml
Labels: bug, refactor

#71 [feat #70] 이메일, 비밀번호로 사용자 정보 조회 api 추가
  dtos/user-dto/src/main/java/request/LoginRequest.java
  services/user/src/main/java/com/ticketPing/user/application/service/UserService.java
  services/user/src/main/java/com/ticketPing/user/presentation/cases/UserErrorCase.java
  services/user/src/main/java/com/ticketPing/user/presentation/controller/UserController.java
Labels: feature

#74 [refactor #73] user service login 함수 이름 변경
  services/user/src/main/java/com/ticketPing/user/application/service/UserService.java
  services/user/src/main/java/com/ticketPing/user/presentation/controller/UserController.java
Labels: feature

#81 [feat #75] 예매 완료 이벤트 연결
  common/src/main/java/common/utils/EventSerializer.java
  docker-compose-build.yml
  docker-compose-kafka.yml
  docker-compose.yml
  services/client-channel/src/main/resources/application.yml
  services/order/build.gradle
  services/order/src/main/java/com/ticketPing/order/application/service/EventApplicationService.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/events/OrderCompletedEvent.java
  services/order/src/main/java/com/ticketPing/order/domain/events/OrderTopic.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/order/src/main/resources/application.yml
  services/queue-manage/src/gatling/java/simulation/WaitingQueueSimulation.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/GeneralTokenResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueApplicationService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/DequeueFirstWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/EnqueueWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/RetrieveWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/CountAvailableSlotsCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/DequeueWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/EnqueueWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/RetrieveWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/events/OrderCompletedEvent.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/AvailableSlots.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WaitingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WorkingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/enums/TokenStatus.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/utils/QueueTokenValueGenerator.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/messaging/EventConsumer.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/redis/RedisExpirationListener.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/redis/RedissonConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/utils/ConfigHolder.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/utils/YmlLoader.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WaitingQueueController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
  services/queue-manage/src/main/resources/application.yml
Labels: feature

#82 [fix #75] 환경 설정 변경
  docker-compose.yml
  services/client-channel/src/main/java/com/ticketPing/client_channel/presentation/controller/QueueInfoPollingController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/messaging/EventConsumer.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WaitingQueueController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
  services/queue-manage/src/main/resources/application.yml
Labels: refactor

#86 [feat #84] 좌석 조회 api 생성
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/SeatResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/SeatRepository.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/exception/SeatExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/success/SeatSuccessCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/SeatController.java
Labels: feature

#87 [fix #75] docker-compose 설정 변경
  docker-compose.yml
Labels: bug

#91 [feat #90] 전체 좌석 캐싱 생성 api 추가
  services/performance/build.gradle
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/entity/RedisSeat.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/SeatRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/config/RedisConfig.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/RedisSeatRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/SeatJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/success/ScheduleSuccessCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/ScheduleController.java
  services/performance/src/main/resources/application.yml
Labels: feature

#95 [feat #94] 좌석 주문 정보 조회 api 추가
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/OrderInfoResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/SeatRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/SeatJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/success/SeatSuccessCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/SeatController.java
Labels: feature

#97 [feat #96] 스케줄 전체 좌석 조회 api 추가
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/OrderInfoResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/SeatResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/DataLoader.java
  services/performance/src/main/java/com/ticketPing/performance/domain/entity/RedisSeat.java
  services/performance/src/main/java/com/ticketPing/performance/domain/entity/Seat.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/SeatRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/config/RedisConfig.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/RedisSeatRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/SeatJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/success/PerformanceSuccessCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/success/ScheduleSuccessCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/PerformanceController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/ScheduleController.java
Labels: feature

#98 [feat #92] 결제 전 ttl 검증 -ing
  docker-compose.yml
  services/payment/Dockerfile
  services/payment/build.gradle
  services/payment/src/main/java/com/ticketPing/payment/application/dto/StripeCreatePaymentResponse.java
  services/payment/src/main/java/com/ticketPing/payment/application/dto/StripeResponseDto.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/StripePaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/cases/PaymentErrorCase.java
  services/payment/src/main/java/com/ticketPing/payment/cases/PaymentSuccessCase.java
  services/payment/src/main/java/com/ticketPing/payment/config/WebConfig.java
  services/payment/src/main/java/com/ticketPing/payment/domain/model/Payment.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/client/ReservationClient.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/redis/RedisConfig.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/redis/RedisLockService.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/StripePaymentController.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/request/StripeRequestDto.java
  services/payment/src/main/resources/application-local.yml
  services/payment/src/test/java/com/ticketPing/payment/application/service/StripePaymentServiceTest.java
Labels: feature

#100 [fix] remove reservationClient
  services/payment/src/main/java/com/ticketPing/payment/application/service/StripePaymentService.java
  services/payment/src/test/java/com/ticketPing/payment/application/service/StripePaymentServiceTest.java
Labels: bug

#102 [refactor #101] 배포 수정사항 업로드
  docker-compose.yml
  gateway/src/main/java/com/ticketping/gateway/config/RouteConfig.java
  services/order/src/main/resources/application.yml
  services/performance/src/main/resources/application.yml
Labels: refactor

#104 [refactor #103] 좌석 캐싱 redis repository에서 redis template으로 수정
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/SeatResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/entity/RedisSeat.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/config/RedisConfig.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/RedisSeatRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/service/RedisService.java
  services/performance/src/main/resources/application.yml
Labels: refactor

#105 [fix] WaitingQueueRepositoryImpl 클래스 dequeueWorkingToken 메서드 수정
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepositoryImpl.java
Labels: bug

#109 [refactor #108] 코드 리팩토링
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueApplicationServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/DeleteFirstWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/FindWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/InsertWaitingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/DeleteWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/FindWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/InsertWorkingTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WaitingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WorkingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/enums/DeleteWorkingTokenCase.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/messaging/EventConsumer.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/redis/RedisExpirationListener.java
Labels: refactor

#117 [test #116] gatling 대기열 진입 부하 테스트
  docker-compose-queue.yml
  services/queue-manage/src/gatling/java/simulation/EnterWaitingQueueSimulation.java
  services/queue-manage/src/gatling/java/simulation/WaitingQueueSimulation.java
  services/queue-manage/src/main/resources/application.yml
Labels: test

#130 [fix] client-channel 설정 삭제
  build.gradle
  settings.gradle
Labels: bug

#133 [fix & refactor #132] : 코드 로직 수정 및 리팩토링
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderSeatInfo.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/orderHttp/OrderHttp.http
Labels: refactor

#134 [feat #20] 결제 승인 API
  dtos/order-dto/src/main/java/dto/PaymentRequestDto.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/StripePaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/domain/model/entity/Payment.java
  services/payment/src/main/java/com/ticketPing/payment/domain/model/enums/PayStatus.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/cases/PaymentSuccessCase.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/StripePaymentController.java
Labels: feature

#136 [feat 135] gateway cors 설정 추가
  gateway/src/main/resources/application.yml
Labels: feature

#138 [feat #137] gateway 인가 필터 추가
  auth/src/main/java/com/ticketPing/auth/presentation/controller/AuthController.java
  gateway/build.gradle
  gateway/src/main/java/com/ticketping/gateway/GatewayApplication.java
  gateway/src/main/java/com/ticketping/gateway/application/dto/UserCache.java
  gateway/src/main/java/com/ticketping/gateway/exception/ApplicationException.java
  gateway/src/main/java/com/ticketping/gateway/infrastructure/config/RedisConfig.java
  gateway/src/main/java/com/ticketping/gateway/infrastructure/repository/RedisRepository.java
  gateway/src/main/java/com/ticketping/gateway/infrastructure/security/JwtFilter.java
  gateway/src/main/java/com/ticketping/gateway/infrastructure/security/SecurityConfig.java
  gateway/src/main/java/com/ticketping/gateway/presentation/cases/ErrorCase.java
  gateway/src/main/java/com/ticketping/gateway/presentation/cases/SecurityErrorCase.java
  gateway/src/main/resources/application.yml
Labels: feature

#141 [fix #140] 대기열 진입 동시성 문제 해결 (카운터 조회 및 토큰 저장)
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/dto/GeneralQueueTokenResponse.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/DeleteFirstWaitingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/FindWaitingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/InsertWaitingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/CountAvailableSlotsCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/DeleteWorkingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/FindWorkingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/InsertWorkingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/AvailableSlots.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/QueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WaitingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WorkingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/SwaggerConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/RedisRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WaitingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/script/InsertWaitingQueueTokenScript.java
Labels: bug

#143 [feat #142] prometheus, grafana 설정 추가
  auth/build.gradle
  auth/src/main/resources/application.yml
  prometheus/docker-compose.yml
  prometheus/prometheus.yml
  services/order/build.gradle
  services/order/src/main/resources/application.yml
  services/payment/build.gradle
  services/payment/src/main/resources/application.yml
  services/performance/build.gradle
  services/performance/src/main/resources/application.yml
  services/queue-manage/build.gradle
  services/queue-manage/src/main/resources/application.yml
  services/user/build.gradle
  services/user/src/main/resources/application.yml
Labels: feature

#145 [fix] repository 에러 수정
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/repository/PaymentRepository.java
Labels: bug

#147 [refactor #146] order 서비스 리팩토링
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderResponse.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderSeatInfo.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/UserReservationDto.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/temp/SeatResponse.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/Order.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/OrderSeat.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/RedisSeat.java
  services/order/src/main/java/com/ticketPing/order/domain/repository/RedisSeatRepository.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/RedisKeyExpiredListener.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/config/RedisConfig.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/config/RedissonConfig.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/repository/OrderRepository.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/repository/OrderSeatRepository.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/service/RedisService.java
  services/order/src/main/java/com/ticketPing/order/presentation/cases/success/OrderSuccessCase.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
Labels: refactor

#149 [refactor #148] 좌석 선점 만료 이벤트 리스너 리팩토링
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderPerformanceDetails.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/temp/SeatRate.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/client/PerformanceService.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/Order.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/OrderSeat.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/RedisKeyExpiredListener.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PerformanceClient.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PerformanceService.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/UserClient.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/service/RedisService.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
Labels: refactor

#151 [fix, feat #150] 에러 해결 및 Stripe Webhook 연동
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/StripePaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/client/OrderClient.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/StripePaymentController.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/StripeWebhookController.java
  services/payment/src/main/resources/application-local.yml
  services/payment/src/main/resources/application.yml
Labels: feature

#153 [refactor #152] 결제 완료 시 OrderStatus 변경 로직 수정
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderResponse.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/UserReservationDto.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/Order.java
  services/order/src/main/java/com/ticketPing/order/domain/model/enums/OrderStatus.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/RedisKeyExpiredListener.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/service/RedisService.java
  services/order/src/main/java/com/ticketPing/order/presentation/cases/exception/OrderExceptionCase.java
  services/order/src/main/java/com/ticketPing/order/presentation/cases/success/OrderSuccessCase.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
Labels: refactor

#155 [refactor #154] redis ttl key에 prfix 추가
  services/payment/src/main/java/com/ticketPing/payment/application/service/StripePaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/redis/RedisLockService.java
Labels: refactor

#156 [refactor #144] 전체 공연 캐싱 일정 단위에서 공연 단위로 변경
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/service/RedisService.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/OrderInfoResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/PerformanceResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/ScheduleResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/SeatResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/PerformanceService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/ScheduleService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/DataInitializer.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/entity/Performance.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/entity/PerformanceHall.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/entity/Schedule.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/entity/Seat.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/entity/SeatCost.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/enums/SeatRate.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceHallRepository.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceRepository.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/ScheduleRepository.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/SeatRepository.java
  services/performance/src/main/java/com/ticketPing/performance/http/Performance.http
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/config/RedisConfig.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/PerformanceHallJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/PerformanceJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/ScheduleJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/SeatJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/exception/SeatExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/PerformanceController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/ScheduleController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/SeatController.java
  services/performance/src/main/resources/application.yml
Labels: refactor

#157 [refactor] no usage bean 삭제
  services/order/src/main/java/com/ticketPing/order/infrastructure/service/RedisService.java
Labels: refactor

#159 [feat #158] docker-compose env 파일 적용
  docker-compose.yml
Labels: feature

#160 [refactor] .dockerignore 위치 이동
  .dockerignore
  .gitignore
Labels: refactor

#162 [refactor #161] 배포용 전체 수정
  auth/src/main/resources/application.yml
  docker-compose.yml
  gateway/src/main/java/com/ticketping/gateway/infrastructure/config/GatewayCorsConfiguration.java
  gateway/src/main/java/com/ticketping/gateway/infrastructure/config/RouteConfig.java
  gateway/src/main/java/com/ticketping/gateway/infrastructure/security/JwtFilter.java
  gateway/src/main/java/com/ticketping/gateway/infrastructure/security/SecurityConfig.java
  gateway/src/main/resources/application.yml
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
Labels: bug, refactor

#164 [feat #129] queue-manage service webflux 전환
  common/src/main/java/common/response/CommonResponse.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/StripePaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/StripePaymentController.java
  services/queue-manage/build.gradle
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueServiceImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/InsertWaitingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/InsertWorkingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WorkingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WaitingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/KafkaConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedissonConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/RedisRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WaitingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/script/InsertWaitingQueueTokenScript.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WaitingQueueController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
Labels: feature

#167 [fix] RedissonConfig 수정
  docker-compose-queue.yml
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedissonConfig.java
  services/queue-manage/src/main/resources/application.yml
Labels: bug

#170 Readme.md 수정
  README.md
Labels: documentation

#172 [refactor #171] queue-manage service 코드 리팩토링
  services/queue-manage/src/gatling/java/simulation/EnterWaitingQueueSimulation.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/QueueManageApplication.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/cases/QueueErrorCase.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/FindWaitingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/InsertWaitingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/DeleteWorkingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/FindWorkingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/InsertWorkingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WaitingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/WorkingQueueToken.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/model/enums/WorkingQueueTokenDeleteCase.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/utils/TokenValueGenerator.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedisConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/listener/EventConsumer.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/listener/RedisExpirationListener.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/RedisRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WaitingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/script/DeleteFirstTokenScript.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/script/SaveTokenScript.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/cases/QueueSuccessCase.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
Labels: refactor

#174 [documentation #173] README.md 인프라 설계서 이미지 수정
  README.md
Labels: documentation

#187 [refactor #186] 대기열 상태 조회 리팩토링
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/cases/QueueErrorCase.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/RedisRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WaitingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/script/DeleteFirstTokenScript.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/script/GetRankAndSizeScript.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/script/SaveTokenScript.java
Labels: refactor
